// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViGraph.Database;

namespace ViGraph.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210816132610_ModelsComplete")]
    partial class ModelsComplete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppFile.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppRole.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppRole.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppRole.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppRole.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppRole.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppRole.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppUser.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppUser.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppUser.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppUser.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppUser.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.AppUser.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Category.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 66,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.Video.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 67,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 68,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 69,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 70,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 71,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 72,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 74,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 75,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 76,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 77,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 78,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 79,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 80,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 81,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 82,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 83,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.VideoViewCount.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 85,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 86,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 87,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 88,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 89,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 90,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 91,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 92,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 93,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 94,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 95,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 96,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 97,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 98,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 99,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 100,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 101,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 102,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTCategory.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 103,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 104,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 105,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 106,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 107,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 108,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 109,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 110,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 111,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 112,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 113,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 114,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 115,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 116,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 117,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 118,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 119,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 120,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTChannel.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 121,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 122,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 123,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 124,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 125,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 126,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 127,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 128,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 129,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 130,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 131,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 132,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 133,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 134,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 135,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 136,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 137,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 138,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTMeta.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 139,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 140,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 141,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 142,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 143,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 144,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 145,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 146,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 147,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 148,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 149,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 150,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 151,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 152,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 153,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 154,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 155,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 156,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylist.ForceDelete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 157,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 158,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Create",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 159,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Create",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 160,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.View",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 161,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.View",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 162,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.View",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 163,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 164,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 165,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Edit",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 166,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Delete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 167,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Delete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 168,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Delete",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 169,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Restore",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 170,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Restore",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 171,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.Restore",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 172,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.ForceDelete",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 173,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.ForceDelete",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 174,
                            ClaimType = "Permission",
                            ClaimValue = "Permissions.YTPlaylistItem.ForceDelete",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("ViGraph.Models.AppFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Initialized','Paused', 'Completed', 'Failed')");

                    b.Property<int>("TotalSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UploadedSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppFile");
                });

            modelBuilder.Entity("ViGraph.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Sef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "f07266a2-af2d-476b-b477-1b484ea613e3",
                            Name = "Super Admin",
                            NormalizedName = "SuperAdmin",
                            Sef = "super-admin"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "f8fcbd81-004e-4b57-8740-e6c4bd1e4c31",
                            Name = "Admin",
                            NormalizedName = "Admin",
                            Sef = "admin"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "9ef4b932-7159-4b44-8c5f-fe57dadf1b6e",
                            Name = "Editor",
                            NormalizedName = "Editor",
                            Sef = "editor"
                        });
                });

            modelBuilder.Entity("ViGraph.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("enum('TR','EN')");

                    b.Property<DateTime?>("LastLogin")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("LastLogin");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLogout")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("LastLogout");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("LockoutEnd");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "z3@vigraph.com",
                            FullName = "Z3 Root",
                            Language = "TR",
                            LockoutEnabled = false,
                            NormalizedUserName = "z3@vigraph.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEEU3N16azoLLcAsQrBHOlZMcEyfvupqL8JkHyDmCRwOhu+dMB6SGXTSaCyJaWxKFUQ==",
                            UserName = "z3@vigraph.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@admin.com",
                            FullName = "Test Admin",
                            Language = "TR",
                            LockoutEnabled = false,
                            NormalizedUserName = "test@admin.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEDiHirzElMi3W/FsHTmcIEbsrBg1zmeiNfrNyijAKNzPXUpQMv2eA9ITfYiy34LEmQ==",
                            UserName = "test@admin.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@editor.com",
                            FullName = "Test Editor",
                            Language = "TR",
                            LockoutEnabled = false,
                            NormalizedUserName = "test@editor.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEGQyChrpv0hDnwDW57v1ZL1WGJIPM7bclXME+sxUTOkE4aDw/fKLSjIn+C0yNqOq3A==",
                            UserName = "test@editor.com"
                        });
                });

            modelBuilder.Entity("ViGraph.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Sef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 16, 16, 26, 10, 103, DateTimeKind.Local).AddTicks(1510),
                            CreatedById = 1,
                            Sef = "gundem",
                            Title = "Gündem"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 16, 16, 26, 10, 103, DateTimeKind.Local).AddTicks(3390),
                            CreatedById = 1,
                            Sef = "spor",
                            Title = "Spor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 16, 16, 26, 10, 103, DateTimeKind.Local).AddTicks(3400),
                            CreatedById = 1,
                            Sef = "yasam",
                            Title = "Yaşam"
                        });
                });

            modelBuilder.Entity("ViGraph.Models.Thumbnail", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("enum('default','medium', 'high', 'standart', 'maxres')");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VideoId");

                    b.HasIndex("FileId", "VideoId", "Size")
                        .IsUnique();

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("ViGraph.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("HDFileId")
                        .HasColumnType("int");

                    b.Property<int>("SDFileId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasColumnType("enum('initialized', 'started', 'deleted','failed', 'processed', 'rejected', 'uploaded')");

                    b.Property<int>("YTCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("YTMetaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HDFileId");

                    b.HasIndex("SDFileId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("YTCategoryId");

                    b.HasIndex("YTMetaId")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("ViGraph.Models.VideoViewCount", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasMaxLength(2147483647)
                        .HasColumnType("int");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("VideoViewCounts");
                });

            modelBuilder.Entity("ViGraph.Models.YTCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Assignable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Etag")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("YTChannelId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("YTId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("YTId")
                        .IsUnique();

                    b.ToTable("YTCategories");
                });

            modelBuilder.Entity("ViGraph.Models.YTChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Etag")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("YTId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("YTId")
                        .IsUnique();

                    b.ToTable("YTChannels");
                });

            modelBuilder.Entity("ViGraph.Models.YTMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Etag")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrivacyStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("PublicStatsViewable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("PublishedAt");

                    b.Property<string>("YTChannelId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("YTId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("YTId")
                        .IsUnique();

                    b.ToTable("YTMetas");
                });

            modelBuilder.Entity("ViGraph.Models.YTPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Etag")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("YTChannelId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("YTId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("YTMetaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("YTId")
                        .IsUnique();

                    b.HasIndex("YTMetaId")
                        .IsUnique();

                    b.ToTable("YTPlaylists");
                });

            modelBuilder.Entity("ViGraph.Models.YTPlaylistItem", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("YTPlaylistId")
                        .HasColumnType("int");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("YTPlaylistId", "Position")
                        .IsUnique();

                    b.ToTable("YTPlaylistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ViGraph.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ViGraph.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViGraph.Models.Category", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ViGraph.Models.Thumbnail", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("File");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ViGraph.Models.Video", b =>
                {
                    b.HasOne("ViGraph.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppFile", "HDFile")
                        .WithMany()
                        .HasForeignKey("HDFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppFile", "SDFile")
                        .WithMany()
                        .HasForeignKey("SDFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("ViGraph.Models.YTCategory", "YTCategory")
                        .WithMany()
                        .HasForeignKey("YTCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.YTMeta", "YTMeta")
                        .WithMany()
                        .HasForeignKey("YTMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("HDFile");

                    b.Navigation("SDFile");

                    b.Navigation("UpdatedBy");

                    b.Navigation("YTCategory");

                    b.Navigation("YTMeta");
                });

            modelBuilder.Entity("ViGraph.Models.VideoViewCount", b =>
                {
                    b.HasOne("ViGraph.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ViGraph.Models.YTPlaylist", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("ViGraph.Models.YTMeta", "YTMeta")
                        .WithMany()
                        .HasForeignKey("YTMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("YTMeta");
                });

            modelBuilder.Entity("ViGraph.Models.YTPlaylistItem", b =>
                {
                    b.HasOne("ViGraph.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViGraph.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("ViGraph.Models.YTPlaylist", "YTPlaylist")
                        .WithMany()
                        .HasForeignKey("YTPlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("YTPlaylist");
                });
#pragma warning restore 612, 618
        }
    }
}
