// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViGraph.Database;

namespace ViGraph.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210810142641_UserFullTextIndex")]
    partial class UserFullTextIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
